### ISSUE TITLE
error: failed to select a version for `quote`.

### ISSUE THREAD

**Issue by phill-85** [redox-os/orbtk#256] opened 2020-07-13 11:04 UTC
Cannot build orbtk on windows 7

`error: failed to select a version for 'quote'.
    ... required by package 'orbtk-proc-macros v0.3.1-alpha3 (https://github.com/redox-os/orbtk.git?branch=develop#cef22710)'
    ... which is depended on by 'orbtk v0.3.1-alpha3 (https://github.com/redox-os/orbtk.git?branch=develop#cef22710)'
versions that meet the requirements '^1.0.3' are: 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3

all possible versions conflict with previously selected packages.

  previously selected package 'quote v1.0.2'
    ... which is depended on by 'cssparser-macros v0.3.6'
    ... which is depended on by 'cssparser v0.17.0'
    ... which is depended on by 'orbtk-css-engine v0.3.1-alpha3 (https://github.com/redox-os/orbtk.git?branch=develop#cef22710)'
    ... which is depended on by 'orbtk v0.3.1-alpha3 (https://github.com/redox-os/orbtk.git?branch=develop#cef22710)'

failed to select a version for 'quote' which could resolve this conflict`

Alpha 2 works fine

**Comment by michalsieron** [comment] 2020-07-17 09:48
Can't reproduce your issue on fresh Win7 VM
Steps I did:
* `git clone https://github.com/redox-os/orbtk`
* `cd orbtk`
* `cargo clean`
* `cargo run --example widgets`

Note: I have compiled for `i686-pc-windows-gnu`

**Comment by FloVanGH** [comment] 2020-07-20 05:17
@phill-85 could you check the latest code of the develop branch?

**Comment by FloVanGH** [comment] 2020-07-22 05:03
@phill-85 does it work?

**Comment by FloVanGH** [comment] 2020-07-24 05:08
I close this now. If you have still that issue you could reopen it.

**Closed by FloVanGH** 2020-07-24 05:08 UTC
Labels: bug
