### ISSUE TITLE
Capital letters in a TextBox

### ISSUE THREAD

**Issue by thivmcthiv** [redox-os/orbtk#240] opened 2020-06-26 20:39 UTC
Hey, I noticed earlier that using shift (or caps lock) doesn't work in textboxes. Is this just a bug on linux, or is it Impossible to use capitals in text boxes? 

Edit:

yeah, it seems to be a bug. Typing in capital letters into TextBoxes works fine on macos, but on ubuntu, typing capital letters doesn't work.

**Comment by FloVanGH** [comment] 2020-06-29 04:23
Thank you for the report. I will check it.

**Comment by uniformbuffer** [comment] 2020-07-26 11:12
Hi, i have also encountered this problem (i'm using an AML-S905X-CC aarch64 linux) and i tried to find what cause it. After some digging seems that the code from Orbtk side is fine. Also, if i have understood correctly, the window backend of *nix systems is "minifb". Since it is used for both linux and mac os, so they share the same code, and, since on mac os work, it is very likely that the problem is in the "minifb" side.

Hope it helped,
Have a good day

**Comment by FloVanGH** [comment] 2020-07-26 14:09
Hi,

thank you for your research, I will check it too and will report it to minifb. This should be definitely fixed before the next release. I will test it also with the upcoming glutin backend.

Thank you

**Comment by kivimango** [comment] 2020-08-02 11:12
Using shift or caps lock in TextBoxes works under Windows 10 (only characters of the English alphabet, but that's another issue)

**Comment by FloVanGH** [comment] 2020-08-13 05:13
Yes looks like it's a problem in minifb I've created an issue https://github.com/emoon/rust_minifb/issues/203. I will postpone this to the 0.3.1-alpha4 release, because the backend should also solve this problem.

**Comment by FloVanGH** [comment] 2020-09-07 17:33
should be fixed now on the orbraq (new default) backend.

**Closed by FloVanGH** 2020-09-07 17:33 UTC
Labels: bug, next
