### ISSUE TITLE
OrbTk application does not start on Wayland

### ISSUE THREAD

**Issue by uniformbuffer** [redox-os/orbtk#292] opened 2020-08-10 15:15 UTC
**Describe the bug**
OrbTk application fail to create window when launched on Wayland based desktop environment.

**To Reproduce**
Run any application on a Wayland based desktop environment.

**Expected behavior**
OrbTk should be able to run on Wayland.

**Screenshots**
The application crash on start with the following error:
```
thread 'main' panicked at 'Failed to create window "XOpenDisplay failed"', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0xaaaac7a66f94 - backtrace::backtrace::libunwind::trace::hda45efcefd90bf1c
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0xaaaac7a66f94 - backtrace::backtrace::trace_unsynchronized::h659c477d8c916672
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0xaaaac7a66f94 - std::sys_common::backtrace::_print_fmt::hfde2e71b87089515
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0xaaaac7a66f94 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd77b322ff62f0331
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0xaaaac7a856fc - core::fmt::write::h9523292fc41e7901
                               at src/libcore/fmt/mod.rs:1076
   5:     0xaaaac7a62a18 - std::io::Write::write_fmt::hff1f8e87eef51cd9
                               at src/libstd/io/mod.rs:1537
   6:     0xaaaac7a693c8 - std::sys_common::backtrace::_print::h1de3ed844bb3ca13
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0xaaaac7a693c8 - std::sys_common::backtrace::print::h4ee04e515562d9dc
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0xaaaac7a693c8 - std::panicking::default_hook::{{closure}}::h2972d84a1dd1b0a3
                               at src/libstd/panicking.rs:198
   9:     0xaaaac7a69108 - std::panicking::default_hook::h2726e9cec6e949b1
                               at src/libstd/panicking.rs:218
  10:     0xaaaac7a69a38 - std::panicking::rust_panic_with_hook::h97393f95b70cea22
                               at src/libstd/panicking.rs:486
  11:     0xaaaac7a69664 - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0xaaaac7a695d8 - std::panicking::begin_panic_fmt::hb28786b72fc6146f
                               at src/libstd/panicking.rs:342
  13:     0xaaaac778c7cc - orbtk_shell::platform::window_builder::WindowBuilder<A>::build::{{closure}}::hfce89adebb45dd92
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:16
  14:     0xaaaac77a77dc - core::result::Result<T,E>::unwrap_or_else::h0c6f0dbe36bb1716
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/result.rs:853
  15:     0xaaaac778b224 - orbtk_shell::platform::window_builder::WindowBuilder<A>::build::h6dd7b1e6c50580da
                               at /home/fabio/.cargo/git/checkouts/orbtk-90d798f349c2ab56/1fee59f/crates/shell/src/minifb/window_builder.rs:117
  16:     0xaaaac76bf16c - orbtk_api::application::Application::window::hb5c3830e66deb8e9
                               at /home/fabio/.cargo/git/checkouts/orbtk-90d798f349c2ab56/1fee59f/crates/api/src/application/mod.rs:65
  17:     0xaaaac7692dac - orbtk_network_widget::main::haa0b78c861340848
                               at src/main.rs:7
  18:     0xaaaac76d6590 - std::rt::lang_start::{{closure}}::h2ad740cd118ed239
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:67
  19:     0xaaaac7a69da8 - std::rt::lang_start_internal::{{closure}}::h7885b4929c5bffc3
                               at src/libstd/rt.rs:52
  20:     0xaaaac7a69da8 - std::panicking::try::do_call::hbf1dd3f84fb6657c
                               at src/libstd/panicking.rs:297
  21:     0xaaaac7a69da8 - std::panicking::try::hd1be8715df9864f2
                               at src/libstd/panicking.rs:274
  22:     0xaaaac7a69da8 - std::panic::catch_unwind::h399b8a216fb6ba73
                               at src/libstd/panic.rs:394
  23:     0xaaaac7a69da8 - std::rt::lang_start_internal::hf64705cd136a0270
                               at src/libstd/rt.rs:51
  24:     0xaaaac76d6568 - std::rt::lang_start::hc3ba98e0d516e4c8
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:67
  25:     0xaaaac7692dfc - main
  26:     0xffff9a8c4158 - __libc_start_main
  27:     0xaaaac7683e18 - <unknown>
```

**Desktop (please complete the following information):**
 - OS: Armbian Buster upgraded to Sid on AML-S905X-CC aarch64 single board computer

**Additional context**
I have put the info about my current system, but i think the problem is simply that the windowing library expect to find Xorg server and not found it. I remember some time ago that OrbTk applications run on Wayland, maybe it is a regression due to backend revamp.
If the problem is caused by the windowing library, maybe there is no need to fix in a short time, simply because, since the upcoming new backend that will use (if i'm not wrong) winit (that have excellent support for Wayland) the problem will, if you can say so, "self fix".

**Comment by FloVanGH** [comment] 2020-08-12 04:28
Thank you for the report.

Yes you are right, the new backend will be build on glutin (winit) and it supports wayland. 

There are some adjustments of the wayland support in minifb, that I not yet merged in my fork. I will try to do it before the next release.

**Comment by FloVanGH** [comment] 2020-08-15 09:05
I've updated minifb could you check if it work now? There is also a OrbClient branch it should work for Wayland.

**Comment by uniformbuffer** [comment] 2020-08-15 12:02
Hi,
on develop branch the application start, but window decoration is missing. I got the same error as https://github.com/redox-os/orbtk/issues/279 : Failed to create server-side surface decoration: Missing
I think that, on wayland protocol, the window is configured to let the server decorate it, but if the server haven't this feature, the window will appear without decoration, making hard to manage (move, resize ecc.)
Also when compiling i got:
```
error[E0308]: mismatched types
   --> /home/fabio/.cargo/git/checkouts/rust_minifb-a9aebf348e927938/8a9d70d/src/os/posix/x11.rs:423:52
    |
423 |                     (d.lib.XInternAtom)(d.display, "_MOTIF_WM_HINTS\0" as *const _ as *const i8, 0);
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `minifb`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I got this kind of error frequently when compiling stuff on wayland. Seems that the *-sys are generated differently for AARCH64 platform and create this strange bugs. Changing that value to u8 fixed the bug. If on your platform (i suppose x86-64?) work correctly, probably there is something wrong on the used binding generator by minifb (probably bindgen).

On the other hands, orbclient work perfectly and compile without problems. (it does not give me the same compile compile error as before, probably because bindings are generated differently using cmake)
Just curious, what is orbclient? Seems to be a sdl2 windowing backend. Very cool!

**Comment by FloVanGH** [comment] 2020-08-15 18:05
Hi, 

thank you for checking!

The problem is that the minifb wayland support is very new and the development of minifb is very slow. Therefore I evaluated some alternatives. My favorite is glutin with pathfinder, it works well, is very fast (Hardware Acceleration) but I have trouble with some systems because of driver issues. Also with other alternatives.

What works best is orbclient with raqote. orbclient is the main window client library on Redox. For redox it is based on a custom solution called orbtial and on other platforms on sdl2. OrbTk earlier based on orbclient but we had some trouble building it on Windows because of sdl2. But now sdl2 for rust provides a features called `bundled` that make it a lot of easier to build it for all platforms. Because of this I evaluate to switch back to orbclient. I think it is for now the most stable and best cross platform solution. On long ran the glutin / pathfinder combination could be an alternative.

**Comment by FloVanGH** [comment] 2020-08-15 18:05
https://gitlab.redox-os.org/redox-os/orbclient

**Comment by FloVanGH** [comment] 2020-08-26 10:06
New default backend orbraq (orbclient | raqote) is now merged to develop and should run on wayland.

**Closed by FloVanGH** 2020-08-26 10:06 UTC
Labels: bug
